export enum ELogCallsActions {
  FETCH_LOG_CALLS = 'FETCH_LOG_CALLS',
  FETCH_LOG_CALLS_REQUEST = 'FETCH_LOG_CALLS_REQUEST',
  FETCH_LOG_CALLS_SUCCESS = 'FETCH_LOG_CALLS_SUCCESS',
  FETCH_LOG_CALLS_FAILED = 'FETCH_LOG_CALLS_FAILED',

  FETCH_LOG_CALL_DETAIL = 'FETCH_LOG_CALL_DETAIL',
  FETCH_LOG_CALL_DETAIL_REQUEST = 'FETCH_LOG_CALL_DETAIL_REQUEST',
  FETCH_LOG_CALL_DETAIL_SUCCESS = 'FETCH_LOG_CALL_DETAIL_SUCCESS',
  FETCH_LOG_CALL_DETAIL_FAILED = 'FETCH_LOG_CALL_DETAIL_FAILED',

  CREATE_LOG_CALL = 'CREATE_LOG_CALL',
  CREATE_LOG_CALL_REQUEST = 'CREATE_LOG_CALL_REQUEST',
  CREATE_LOG_CALL_SUCCESS = 'CREATE_LOG_CALL_SUCCESS',
  CREATE_LOG_CALL_FAILED = 'CREATE_LOG_CALL_FAILED',
}
