export enum ECustomersActions {
  FETCH_CUSTOMERS = 'FETCH_CUSTOMERS',
  FETCH_CUSTOMERS_REQUEST = 'FETCH_CUSTOMERS_REQUEST',
  FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS',
  FETCH_CUSTOMERS_FAILED = 'FETCH_CUSTOMERS_FAILED',

  FETCH_CUSTOMER = 'FETCH_CUSTOMER',
  FETCH_CUSTOMER_REQUEST = 'FETCH_CUSTOMER_REQUEST',
  FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS',
  FETCH_CUSTOMER_FAILED = 'FETCH_CUSTOMER_FAILED',

  CREATE_CUSTOMER = 'CREATE_CUSTOMER',
  CREATE_CUSTOMER_REQUEST = 'CREATE_CUSTOMER_REQUEST',
  CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS',
  CREATE_CUSTOMER_FAILED = 'CREATE_CUSTOMER_FAILED',

  UPDATE_CUSTOMER = 'UPDATE_CUSTOMER',
  UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST',
  UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS',
  UPDATE_CUSTOMER_FAILED = 'UPDATE_CUSTOMER_FAILED',
}
