export enum EAnalyticsActions {
  FETCH_ANALYTICS = "FETCH_ANALYTICS",
  FETCH_ANALYTICS_LEADS_REQUEST = "FETCH_ANALYTICS_LEADS_REQUEST",
  FETCH_ANALYTICS_LEADS_SUCCESS = "FETCH_ANALYTICS_LEADS_SUCCESS",
  FETCH_ANALYTICS_LEADS_FAILED = "FETCH_ANALYTICS_LEADS_FAILED",

  FETCH_ANALYTICS_LOGCALLS_REQUEST = "FETCH_ANALYTICS_LOGCALLS_REQUEST",
  FETCH_ANALYTICS_LOGCALLS_SUCCESS = "FETCH_ANALYTICS_LOGCALLS_SUCCESS",
  FETCH_ANALYTICS_LOGCALLS_FAILED = "FETCH_ANALYTICS_LOGCALLS_FAILED",

  FETCH_ANALYTICS_CUSTOMERS_REQUEST = "FETCH_ANALYTICS_CUSTOMERS_REQUEST",
  FETCH_ANALYTICS_CUSTOMERS_SUCCESS = "FETCH_ANALYTICS_CUSTOMERS_SUCCESS",
  FETCH_ANALYTICS_CUSTOMERS_FAILED = "FETCH_ANALYTICS_CUSTOMERS_FAILED",

  FETCH_ANALYTICS_TOTAL_DURATION_REQUEST = "FETCH_ANALYTICS_TOTAL_DURATION_REQUEST",
  FETCH_ANALYTICS_TOTAL_DURATION_SUCCESS = "FETCH_ANALYTICS_TOTAL_DURATION_SUCCESS",
  FETCH_ANALYTICS_TOTAL_DURATION_FAILED = "FETCH_ANALYTICS_TOTAL_DURATION_FAILED",

  FETCH_ANALYTICS_CONVERSION_RATE_REQUEST = "FETCH_ANALYTICS_CONVERSION_RATE_REQUEST",
  FETCH_ANALYTICS_CONVERSION_RATE_SUCCESS = "FETCH_ANALYTICS_CONVERSION_RATE_SUCCESS",
  FETCH_ANALYTICS_CONVERSION_RATE_FAILED = "FETCH_ANALYTICS_CONVERSION_RATE_FAILED",
}
