export enum EProjectsActions {
  FETCH_PROJECTS = 'FETCH_PROJECTS',
  FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST',
  FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS',
  FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED',

  FETCH_PROJECT_DETAIL = 'FETCH_PROJECT_DETAIL',
  FETCH_PROJECT_DETAIL_REQUEST = 'FETCH_PROJECT_DETAIL_REQUEST',
  FETCH_PROJECT_DETAIL_SUCCESS = 'FETCH_PROJECT_DETAIL_SUCCESS',
  FETCH_PROJECT_DETAIL_FAILED = 'FETCH_PROJECT_DETAIL_FAILED',

  CREATE_PROJECT = 'CREATE_PROJECT',
  CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST',
  CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS',
  CREATE_PROJECT_FAILED = 'CREATE_PROJECT_FAILED',

  UPDATE_PROJECT = 'UPDATE_PROJECT',
  UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST',
  UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS',
  UPDATE_PROJECT_FAILED = 'UPDATE_PROJECT_FAILED',

  CREATE_PROJECT_DESIGN = 'CREATE_PROJECT_DESIGN',
  CREATE_PROJECT_DESIGN_REQUEST = 'CREATE_PROJECT_DESIGN_REQUEST',
  CREATE_PROJECT_DESIGN_SUCCESS = 'CREATE_PROJECT_DESIGN_SUCCESS',
  CREATE_PROJECT_DESIGN_FAILED = 'CREATE_PROJECT_DESIGN_FAILED',

  FETCH_PROJECT_DESIGN = 'FETCH_PROJECT_DESIGN',
  FETCH_PROJECT_DESIGN_REQUEST = 'FETCH_PROJECT_DESIGN_REQUEST',
  FETCH_PROJECT_DESIGN_SUCCESS = 'FETCH_PROJECT_DESIGN_SUCCESS',
  FETCH_PROJECT_DESIGN_FAILED = 'FETCH_PROJECT_DESIGN_FAILED',

  FETCH_PROJECT_DESIGN_BY_DOMAIN = 'FETCH_PROJECT_DESIGN_BY_DOMAIN',
  FETCH_PROJECT_DESIGN_BY_DOMAIN_REQUEST = 'FETCH_PROJECT_DESIGN_BY_DOMAIN_REQUEST',
  FETCH_PROJECT_DESIGN_BY_DOMAIN_SUCCESS = 'FETCH_PROJECT_DESIGN_BY_DOMAIN_SUCCESS',
  FETCH_PROJECT_DESIGN_BY_DOMAIN_FAILED = 'FETCH_PROJECT_DESIGN_BY_DOMAIN_FAILED',

  VALIDATE_DOMAIN = 'VALIDATE_DOMAIN',
  VALIDATE_DOMAIN_REQUEST = 'VALIDATE_DOMAIN_REQUEST',
  VALIDATE_DOMAIN_SUCCESS = 'VALIDATE_DOMAIN_SUCCESS',
  VALIDATE_DOMAIN_FAILED = 'VALIDATE_DOMAIN_FAILED',
}
