export enum ECommentsActions {
  FETCH_COMMENTS_BY_ID = 'FETCH_COMMENTS_BY_ID',
  FETCH_COMMENTS_BY_ID_REQUEST = 'FETCH_COMMENTS_BY_ID_REQUEST',
  FETCH_COMMENTS_BY_ID_SUCCESS = 'FETCH_COMMENTS_BY_ID_SUCCESS',
  FETCH_COMMENTS_BY_ID_FAILED = 'FETCH_COMMENTS_BY_ID_FAILED',

  CREATE_COMMENT = 'CREATE_COMMENT',
  CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST',
  CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS',
  CREATE_COMMENT_FAILED = 'CREATE_COMMENT_FAILED',
}
