export enum EProductsActions {
    FETCH_PRODUCTS = 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST',
    FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED',
  
    FETCH_PRODUCT = 'FETCH_PRODUCT',
    FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST',
    FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED',

    UPDATE_PRODUCT = 'UPDATE_PRODUCT',
    UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED',

    CREATE_PRODUCT = 'CREATE_PRODUCT',
    CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILED = 'CREATE_PRODUCT_FAILED',
}
  