export enum ELeadsActions {
  FETCH_LEADS = 'FETCH_LEADS',
  FETCH_LEADS_REQUEST = 'FETCH_LEADS_REQUEST',
  FETCH_LEADS_SUCCESS = 'FETCH_LEADS_SUCCESS',
  FETCH_LEADS_FAILED = 'FETCH_LEADS_FAILED',

  FETCH_LEAD = 'FETCH_LEAD',
  FETCH_LEAD_REQUEST = 'FETCH_LEAD_REQUEST',
  FETCH_LEAD_SUCCESS = 'FETCH_LEAD_SUCCESS',
  FETCH_LEAD_FAILED = 'FETCH_LEAD_FAILED',

  CREATE_LEAD = 'CREATE_LEAD',
  CREATE_LEAD_REQUEST = 'CREATE_LEAD_REQUEST',
  CREATE_LEAD_SUCCESS = 'CREATE_LEAD_SUCCESS',
  CREATE_LEAD_FAILED = 'CREATE_LEAD_FAILED',

  UPDATE_LEAD = 'UPDATE_LEAD',
  UPDATE_LEAD_REQUEST = 'UPDATE_LEAD_REQUEST',
  UPDATE_LEAD_SUCCESS = 'UPDATE_LEAD_SUCCESS',
  UPDATE_LEAD_FAILED = 'UPDATE_LEAD_FAILED',

  CONVERT_LEAD_TO_CUSTOMER = 'CONVERT_LEAD_TO_CUSTOMER',
  CONVERT_LEAD_TO_CUSTOMER_REQUEST = 'CONVERT_LEAD_TO_CUSTOMER_REQUEST',
  CONVERT_LEAD_TO_CUSTOMER_SUCCESS = 'CONVERT_LEAD_TO_CUSTOMER_SUCCESS',
  CONVERT_LEAD_TO_CUSTOMER_FAILED = 'CONVERT_LEAD_TO_CUSTOMER_FAILED',

  POST_LEAD_ATTACHMENTS_BY_ID = 'POST_LEAD_ATTACHMENTS_BY_ID',
  POST_LEAD_ATTACHMENTS_BY_ID_REQUEST = 'POST_LEAD_ATTACHMENTS_BY_ID_REQUEST',
  POST_LEAD_ATTACHMENTS_BY_ID_SUCCESS = 'POST_LEAD_ATTACHMENTS_BY_ID_SUCCESS',
  POST_LEAD_ATTACHMENTS_BY_ID_FAILED = 'POST_LEAD_ATTACHMENTS_BY_ID_FAILED',
}
